INSERT INTO products (name, category, price, description, emoji, stock) VALUES
('Aromatic Mombati', 'candle', 450, 'Hand-poured aromatic candle made with natural wax. Perfect for creating a peaceful ambiance in your home. Available in lavender, rose, and jasmine scents.', '🕯️', 25),
('Designer Mombati Set', 'candle', 1200, 'Set of 4 decorative candles with intricate hand-carved designs. Made from premium beeswax with long burn time.', '✨', 15),
('Floating Mombati', 'candle', 350, 'Beautiful floating candles for bowls and fountains. Creates magical atmosphere for parties and special occasions.', '🌙', 40),
('Scented Mombati Box', 'candle', 850, 'Gift box with 6 assorted scented candles. Sandalwood, vanilla, cinnamon, rose, lemongrass, and ocean breeze.', '📦', 18),
('Art Dress - Floral', 'dress', 3500, 'Hand-painted floral art dress on pure cotton fabric. Each piece is unique with traditional motifs and vibrant colors.', '👗', 12),
('Embroidered Kurti', 'dress', 2800, 'Beautifully hand-embroidered kurti with traditional threadwork. Made from comfortable cotton blend fabric.', '🥻', 10),
('Handwoven Stole', 'dress', 1500, 'Elegant handwoven stole with traditional patterns. Lightweight and perfect for all seasons.', '🧣', 20),
('Macrame Wall Hanging', 'decor', 2200, 'Handcrafted macrame wall hanging made from natural cotton rope. Adds bohemian charm to any room.', '🖼️', 8),
('Painted Vase', 'decor', 1800, 'Hand-painted ceramic vase with traditional art. Each piece is uniquely crafted by local artisans.', '🏺', 14),
('Dream Catcher', 'decor', 900, 'Traditional handmade dream catcher with feathers and beads. Brings positive energy to your space.', '🌏', 20),
('Decorative Tray', 'decor', 1400, 'Hand-painted wooden serving tray with intricate mandala designs. Functional art for your home.', '🧺', 12),
('Gift Hamper - Premium', 'decor', 3000, 'Curated gift hamper with candle, handmade soap, and a small art piece. Perfect for gifting.', '🎁', 10),
('Natural Handmade Soap', 'soap', 150, 'Handmade cold-process soap with natural oils and herbal extracts. Gentle on skin with a fresh natural fragrance.', '🧼', 50),
('Herbal Beauty Gift Set', 'soap', 650, 'Gift set with handmade soap, body scrub and lip balm. Packed in a beautiful jute bag, perfect for gifting.', '🎀', 25),
('Handmade Beaded Necklace', 'jewelry', 450, 'Beautiful handmade necklace with colorful beads and stone work. Lightweight and unique in design.', '📿', 30),
('Traditional Earrings Set', 'jewelry', 250, 'Handcrafted traditional earrings with intricate design. Available in gold and silver shades.', '💍', 40),
('Jute Shopping Bag', 'bags', 400, 'Eco-friendly handwoven jute shopping bag with cotton lining. Strong, durable and reusable.', '👜', 60),
('Handmade Clutch Purse', 'bags', 550, 'Beautifully embroidered clutch purse made by local artisans. Perfect for parties and special occasions.', '👛', 35),
('Puja Flower Basket', 'festive', 500, 'Traditional decorative basket for puja and festivals. Hand-woven with bamboo and colorful ribbons.', '🧺', 45),
('Durga Puja Special Decor', 'festive', 800, 'Festival special decorative item set with kash and terracotta elements. Perfect for puja pandal home decoration.', '🏵️', 20),
('Jute Table Runner', 'jute', 600, 'Elegant handwoven jute table runner with lace border. Natural and eco-friendly home decor.', '🧶', 30),
('Jute Wall Hanging', 'jute', 700, 'Handmade jute wall hanging with macrame design. Adds a rustic eco-friendly charm to your home.', '🪅', 25);